Table users {
  id int [pk, increment]
  user_name varchar
  email varchar
  user_password varchar
  user_role varchar
}

Table destinations {
  id int [pk, increment]
  city varchar
  country varchar
  image_url varchar
  destination_description text
}

Table flights {
  id int [pk, increment]
  airline varchar
  departure_city varchar
  destination_city varchar
  departure_airport varchar
  destination_airport varchar
  flight_duration varchar
}

Table accommodations {
  id int [pk, increment]
  hotel_name varchar
  hotel_type varchar
  hotel_city varchar
  hotel_location varchar
  amenities text
}

Table trips {
  id int [pk, increment]
  title varchar
  trip_description text
  start_date date
  end_date date
  duration_days int
  keywords text
  destination_id int
  flight_id int
  accommodation_id int
}

Table tripprices {
  id int [pk, increment]
  trip_id int
  tripprice_provider varchar
  price decimal
  tripprice_type varchar
}

Table favorites {
  id int [pk, increment]
  user_id int
  trip_id int
}

Table contactmessages {
  id int [pk, increment]
  email varchar
  contactmessage_subject varchar
  contactmessage_message text
  created_at datetime
}

Ref: trips.destination_id > destinations.id
Ref: trips.flight_id > flights.id
Ref: trips.accommodation_id > accommodations.id

Ref: tripprices.trip_id > trips.id

Ref: favorites.user_id > users.id
Ref: favorites.trip_id > trips.id

// Flights have diffeerent airlines? 
// How to show that in the website?


